### PR TITLE
95e - add 95th Percentile calculations on five minute averages

### PR DESCRIPTION
**Pull request by jessereynolds**
The builder now lets you enable 95th Percentile calculation on a profile. This requires there to be source data samples in the RRD files that are either in five minute intervals, or a divisor of five minutes (eg 150 seconds, 60 seconds, 30 seconds, 10 seconds, 1 second etc.)

### CODE REVIEW

**Comment by jessereynolds** [comment]
All the tests now pass, and there's a test for 95th percentile data now too.

**Comment by auxesis** [comment]
Currently getting this in the builder: 

```
Uncaught TypeError: Cannot call method 'empty' of null
```

This happens at a url not too dissimilar to this:

http://localhost:9292/builder#hosts=router.example.org|metrics=snmp/if_octets-GigabitEthernet0_0_3.693

**Comment by auxesis** [comment]
``` cucumber
When you go to an existing profile that's doing the 95th percentile graphing
And I click "edit profile"
Then the 95th percentile checkbox should be checked
```

Currently it isn't.

**Comment by jessereynolds** [comment]
The error "Uncaught TypeError: Cannot call method 'empty' of null" was due to my running up an older version of the codebase, this error went away after I did a pull from the 95e brach, apologies for the confusion.

**Comment by jessereynolds** [comment]
There is an issue where sometimes the 95th percentile is above the maxima of the graph so it is not shown as it's "off the chart". The graph needs to include the 95th percentile value when calculating the y scale

**Pull request merged**
